### ISSUE TITLE
Replacing Variables with a Schema

### ISSUE THREAD

**Issue by apdibbo** [quattor/template-library-openstack#24]
It would be great to be able to replace all of the variables used in this template library with a schema somewhere within the tree so that we can enforce validation on the variables and so we can easily document what variables do.

**Comment by guillaume-philippon** [comment]
We definitly must have schema for OpenStack configuration but keep some variable to provide a configuration buddle for quattor user.

**Comment by jouvin** [comment]
Adding a schema should be done at the metaconfig level, not at the variable level... Probably we should no accept anymore a service managed by metaconfig without a schema.

**Comment by jrha** [comment]
Discussion at the workshop settled on
1. Generating documentation from Pan annotations
2. Assigning schemas to all metaconfig usage within the template library

**Comment by apdibbo** [comment]
Adding annotations and general schemas for common config is now addressed as of #35
