### ISSUE TITLE
Avoid HA specific variable and make it "the standard"

### ISSUE THREAD

**Issue by guillaume-philippon** [quattor/template-library-openstack#36]
Hi,

We currently having a specific set of variable for HA services which are mainly a list of hosts instead of host.

It could be a good thing to use xxx_HOSTS as standard variable and remove xxx_HOST variable and if the lenght of HOSTS is one consider it as a non-HA service.

Do someone see any issue with this approch ? 

Regards,

**Comment by apdibbo** [comment]
Seems sensible, I will prepare a PR

**Comment by apdibbo** [comment]
Addressed in #37

**Comment by guillaume-philippon** [comment]
I think we could close this ticket as it s redondant w/ the pull request, isn't it ?

**Comment by apdibbo** [comment]
Closing
