### ISSUE TITLE
template cleanup for pike

### ISSUE THREAD

**Issue by stdweird** [quattor/template-library-openstack#44]
there obviously has been a huge effort in creating the current templates, but it looks like there is the possibility for some cleanup.
we are willing to provide some effort here but we have some questions:
* we don't have any setup now, so we can start with an ocata branch. but the cleanup i envsion is non-trivial, and existing sites might want ot switch to ocata before; so i propose we create a pike branch and start there. we will try to follow up the work for ocata and adjust were needed

wrt cleanup, there are some things i would like to see changed:
* some syntax / style cleanup
  * i guess this is not that controversial, we could do that in an ocata branch

* make a component to address a few issues:
 * there are scripts (long, non-trivial ones, no `set -e`, lots of copy/paste)
 * TT rendering: metaconfig with tiny is nice, but some additional structure in the schema seems a good thing, which requires non-trivial rendering
 * there's a lot of `extensible` in the schema and types. i'm aware that having the full schema might too much, but schema vaiidation is a good thing to have. maybe we can generate the schema from the source or documentation?

**Comment by apdibbo** [comment]
Most of this is stuff that I would like to do anyway but have limited bandwidth to do the work.

I am hoping to be moving to Ocata soon so would be happy to help with the work and testing.

Additional structure and schema work would be good

**Comment by stdweird** [comment]
@apdibbo can someone create the ocata branch, so i can start to make simple cleanup PRs to it?

**Comment by apdibbo** [comment]
@stdweird I have pushed that now.

**Comment by stdweird** [comment]
@apdibbo thanks!

**Comment by jrha** [comment]
This won't ever happen for pike now, hopefully the latest (xena) templates are better in this regard.
